/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyUI;

import Data.ConnectDB;
import Models.account;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class JpQuanLyTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLyTaiKhoan
     */
    public ConnectDB cn = new ConnectDB();
    public static JpQuanLyTaiKhoan taikhoan;

    public JpQuanLyTaiKhoan() {
        initComponents();
        taikhoan = this;
        fillTableTaikhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenTk = new javax.swing.JTextField();
        lbTongsotaikhoan = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAccount);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel1.setText("Tìm tài khoản");

        txtTenTk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenTkKeyReleased(evt);
            }
        });

        lbTongsotaikhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongsotaikhoan.setText("Tổng số tài khoản:");

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 204, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 204, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 204, 204));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("1: Admin 2: Nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(txtTenTk, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnThem)
                        .addGap(95, 95, 95)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTongsotaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtTenTk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongsotaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenTkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenTkKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ID");
        table.addColumn("Tên đăng nhập");
        //table.addColumn("Mật khẩu");
        table.addColumn("Quyền truy cập");
        ArrayList<account> arrayAccount = new ArrayList<>();
        arrayAccount = cn.SearchTaiKhoan(txtTenTk.getText());
        int tongtk = 0;
        if (arrayAccount.size() > 0) {

            for (account tk : arrayAccount) {
                tongtk++;
                table.addRow(new Object[]{tk.getId(), tk.getUsername(), tk.getLoaiTk()});
            }
            lbTongsotaikhoan.setText("Tổng số tài khoản: " + tongtk);

        } else {
            lbTongsotaikhoan.setText("Tổng số tài khoản: " + 0);
        }
        jTableAccount.setModel(table);
        for (int i = 0; i < jTableAccount.getColumnCount(); i++) {
            Class<?> col = jTableAccount.getClass();
            jTableAccount.setDefaultEditor(col, null);
        }

    }//GEN-LAST:event_txtTenTkKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DlThemTaiKhoan themtk = new DlThemTaiKhoan(MainUI.ManagerForm.main, true);
        themtk.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        int[] dsXoa = jTableAccount.getSelectedRows();
        if (dsXoa.length <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản để xóa!");
        }
        else
        {
            ArrayList<Integer> listMataikhoan = new ArrayList<Integer>();
            String maTK = "";
            for (int i : dsXoa) {
                int ma = (int) jTableAccount.getValueAt(i, 0);
                listMataikhoan.add(ma);
                String tenTK = (String) jTableAccount.getValueAt(i, 1);
                maTK += tenTK + " \n";
            }
            int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa tài khoản: " + maTK, "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                boolean isXoa = cn.DeleteTaiKhoan(listMataikhoan);
                if (isXoa) {
                    taikhoan.fillTableTaikhoan();
                    taikhoan.updateUI();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Không xóa được tài khoản!");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    public void fillTableTaikhoan() {
        ArrayList<account> arrayAccount = cn.getListaccount();
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ID");
        table.addColumn("Tên đăng nhập");
        //table.addColumn("Mật khẩu");
        table.addColumn("Quyền truy cập");
        int tongTk = 0;
        if (arrayAccount.size() > 0) {

            for (account object : arrayAccount) {
                tongTk++;
                table.addRow(new Object[]{object.getId(), object.getUsername(), object.getLoaiTk()});
            }
            jTableAccount.setModel(table);
            lbTongsotaikhoan.setText("Tổng số tài khoản: " + tongTk);
        } else {
            JOptionPane.showMessageDialog(null, "Không có tài khoản!");
            lbTongsotaikhoan.setText("Tổng số tài khoản: " + tongTk);
        }
        for (int i = 0; i < jTableAccount.getColumnCount(); i++) {
            Class<?> col = jTableAccount.getColumnClass(i);
            jTableAccount.setDefaultEditor(col, null);
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int row = -1;
        row = jTableAccount.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần sửa thông tin!");
        }
        else
        {
            int matk = (int )jTableAccount.getValueAt(row, 0);
            DlSuaTaiKhoan suaBan = new DlSuaTaiKhoan(MainUI.ManagerForm.main, true, matk);
            suaBan.setVisible(true);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccount;
    private javax.swing.JLabel lbTongsotaikhoan;
    private javax.swing.JTextField txtTenTk;
    // End of variables declaration//GEN-END:variables
}
