/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyUI;

import Data.ConnectDB;
import Models.Ban;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class JpQuanLyBan extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLyBan
     */
    public static JpQuanLyBan ban;
    ConnectDB cn = new ConnectDB();
    public JpQuanLyBan() {
        initComponents();
        ban = this;
        fillBanTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JtableBan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMaban = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbTongsoban = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        JtableBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtableBan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel1.setText("Tìm bàn");

        txtMaban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMabanKeyReleased(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 204, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 204, 204));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 204, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lbTongsoban.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongsoban.setText("Tổng số bàn:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtMaban, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnThem)
                        .addGap(77, 77, 77)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongsoban, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtMaban, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTongsoban, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMabanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMabanKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Mã bàn");
        table.addColumn("Tên bàn");
        table.addColumn("Trạng thái");
        ArrayList<Ban> arrayBan = new ArrayList<>();
        arrayBan = cn.SearchBan(txtMaban.getText());
        if (arrayBan.size() > 0) {
            int  tongBan = 0;
            for (Ban ban : arrayBan) {
                tongBan++;
                table.addRow(new Object[]{ban.GetMaBan(), ban.GetTenBan(), ban.GetTrangThai()});
            }
            lbTongsoban.setText("Tổng số bàn: " + tongBan);
            
        }
        else
        {
            lbTongsoban.setText("Tổng số bàn: " + 0);
        }
        JtableBan.setModel(table);
        for (int i = 0; i < JtableBan.getColumnCount(); i++) {
            Class<?> col = JtableBan.getClass();
            JtableBan.setDefaultEditor(col, null);           
        }
        
    }//GEN-LAST:event_txtMabanKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int[] dsXoa = JtableBan.getSelectedRows();
        if (dsXoa.length <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn để xóa!");
        }
        else
        {
            ArrayList<Integer> listMaban = new ArrayList<Integer>();
            String maBan = "";
            for (int i : dsXoa) {
                int ma = (int) JtableBan.getValueAt(i, 0);
                listMaban.add(ma);
                String tenban = (String) JtableBan.getValueAt(i, 1);
                maBan += tenban + " \n"; 
            }
            int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa bàn: " + maBan, "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                boolean isXoa = cn.DeleteBan(listMaban);
                if (isXoa) {
                    ban.fillBanTable();
                    ban.updateUI();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Không xóa được bàn!");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       
        int row = -1;
        row = JtableBan.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn cần sửa thông tin!");
        }
        else
        {
            int maban = (int )JtableBan.getValueAt(row, 0);
            DlSuaBan suaBan = new DlSuaBan(MainUI.ManagerForm.main, true, maban);
            suaBan.setVisible(true);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DlThemBan themban = new DlThemBan(MainUI.ManagerForm.main, true);
        themban.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableBan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTongsoban;
    private javax.swing.JTextField txtMaban;
    // End of variables declaration//GEN-END:variables

    public void fillBanTable() {
        ArrayList<Ban> arrayBan = new ArrayList<>();
        arrayBan = cn.GetBan(0);
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Mã bàn");
        table.addColumn("Tên bàn");
        table.addColumn("Trạng thái");
        if (arrayBan.size() > 0) {
            int tongBan = 0;
            for (Ban ban1 : arrayBan) {
                tongBan++;
                table.addRow(new Object[]{ban1.GetMaBan(), ban1.GetTenBan(), ban1.GetTrangThai()});
            }
            lbTongsoban.setText("Tổng số bàn: " + tongBan);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Không có bàn!");
        }
        JtableBan.setModel(table);
        for (int i = 0; i < JtableBan.getColumnCount(); i++) {
            Class<?> col = JtableBan.getColumnClass(i);
            JtableBan.setDefaultEditor(col, null);
        }
    }
}
