/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyUI;

import java.awt.BorderLayout;

/**
 *
 * @author pc
 */
public class JpQuanLy extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLy
     */
    public JpQuanLy() {
        initComponents();
        fillQlTaiKhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpButton = new javax.swing.JPanel();
        btnQltaikhoan = new javax.swing.JButton();
        btnQlBan = new javax.swing.JButton();
        BtnQuanlyMon = new javax.swing.JButton();
        BtnQlThucDon = new javax.swing.JButton();
        jpSettingContent = new javax.swing.JPanel();

        jpButton.setBackground(new java.awt.Color(204, 255, 204));
        jpButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnQltaikhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQltaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quanlytaikhoan.png"))); // NOI18N
        btnQltaikhoan.setText("Quản lý tài khoản");
        btnQltaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQltaikhoanActionPerformed(evt);
            }
        });

        btnQlBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQlBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quanlyban.png"))); // NOI18N
        btnQlBan.setText("Quản lý bàn");
        btnQlBan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQlBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlBanActionPerformed(evt);
            }
        });

        BtnQuanlyMon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnQuanlyMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quanlymon.png"))); // NOI18N
        BtnQuanlyMon.setText("Quản lý món");
        BtnQuanlyMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuanlyMonActionPerformed(evt);
            }
        });

        BtnQlThucDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnQlThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quanlymenu.png"))); // NOI18N
        BtnQlThucDon.setText("Quản lý thực đơn ");
        BtnQlThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQlThucDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonLayout = new javax.swing.GroupLayout(jpButton);
        jpButton.setLayout(jpButtonLayout);
        jpButtonLayout.setHorizontalGroup(
            jpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnQuanlyMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQlBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQltaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnQlThucDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpButtonLayout.setVerticalGroup(
            jpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnQltaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnQlBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BtnQlThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BtnQuanlyMon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jpSettingContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpSettingContentLayout = new javax.swing.GroupLayout(jpSettingContent);
        jpSettingContent.setLayout(jpSettingContentLayout);
        jpSettingContentLayout.setHorizontalGroup(
            jpSettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        jpSettingContentLayout.setVerticalGroup(
            jpSettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpSettingContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSettingContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQltaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQltaikhoanActionPerformed
        // TODO add your handling code here:
        fillQlTaiKhoan();
       
    }//GEN-LAST:event_btnQltaikhoanActionPerformed

    private void btnQlBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlBanActionPerformed
        // TODO add your handling code here:
        fillQlBan();
    }//GEN-LAST:event_btnQlBanActionPerformed

    private void BtnQuanlyMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuanlyMonActionPerformed
        // TODO add your handling code here:
        fillQlMon();
    }//GEN-LAST:event_BtnQuanlyMonActionPerformed

    private void BtnQlThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQlThucDonActionPerformed
        // TODO add your handling code here:
        fillQlLoaiMon();
    }//GEN-LAST:event_BtnQlThucDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnQlThucDon;
    private javax.swing.JButton BtnQuanlyMon;
    private javax.swing.JButton btnQlBan;
    private javax.swing.JButton btnQltaikhoan;
    private javax.swing.JPanel jpButton;
    private javax.swing.JPanel jpSettingContent;
    // End of variables declaration//GEN-END:variables

    private void fillQlTaiKhoan() {
       jpSettingContent.removeAll();
       JpQuanLyTaiKhoan tk = new JpQuanLyTaiKhoan();
       jpSettingContent.setLayout(new BorderLayout());
       jpSettingContent.add(tk);
    }
    private void fillQlBan(){
       jpSettingContent.removeAll();
       JpQuanLyBan tk = new JpQuanLyBan();
       jpSettingContent.setLayout(new BorderLayout());
       jpSettingContent.add(tk);
    }
    private void fillQlMon(){
       jpSettingContent.removeAll();
       JpQuanLyMon tk = new JpQuanLyMon();
       jpSettingContent.setLayout(new BorderLayout());
       jpSettingContent.add(tk);
    }
    private void fillQlLoaiMon(){
       jpSettingContent.removeAll();
       JpQuanLyLoaiMon tk = new JpQuanLyLoaiMon();
       jpSettingContent.setLayout(new BorderLayout());
       jpSettingContent.add(tk);
    }
}
