/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyUI;

import Data.ConnectDB;
import Models.Loai;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class JpQuanLyLoaiMon extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLyLoaiMon
     */
    public ConnectDB cn = new ConnectDB();
    public static JpQuanLyLoaiMon loaiMon;
    public JpQuanLyLoaiMon() {
        initComponents();
        fillTableLoaiMon();
        loaiMon = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpquanlymon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableLoai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbTongsoloai = new javax.swing.JLabel();

        jpquanlymon.setBackground(new java.awt.Color(255, 255, 255));

        JtableLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtableLoai);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel1.setText("Tìm nhóm món");

        txtTenLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenLoaiKeyReleased(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 204, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 204, 204));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 204, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lbTongsoloai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongsoloai.setText("Tổng số nhóm món:");

        javax.swing.GroupLayout jpquanlymonLayout = new javax.swing.GroupLayout(jpquanlymon);
        jpquanlymon.setLayout(jpquanlymonLayout);
        jpquanlymonLayout.setHorizontalGroup(
            jpquanlymonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpquanlymonLayout.createSequentialGroup()
                .addGroup(jpquanlymonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpquanlymonLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpquanlymonLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnThem)
                        .addGap(77, 77, 77)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpquanlymonLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jpquanlymonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongsoloai, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jpquanlymonLayout.setVerticalGroup(
            jpquanlymonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpquanlymonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpquanlymonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpquanlymonLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTongsoloai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jpquanlymonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpquanlymon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpquanlymon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void fillTableLoaiMon(){
        ArrayList<Loai>  arrayLoai  = new ArrayList<>();
        arrayLoai = cn.GetLoai();
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Mã nhóm");
        table.addColumn("Tên nhóm thực đơn");
        table.addColumn("Màu sắc");
        int tongLoai = 0;
        if (arrayLoai.size()> 0) {
            
            for (Loai loai : arrayLoai) {
                tongLoai++;
                table.addRow(new Object[] {loai.GetMaLoai(), loai.GetTenLoai(), loai.GetMauSac()});
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Không có nhóm thực đơn!");      
        }
        JtableLoai.setModel(table);
        lbTongsoloai.setText("Tổng số nhóm món: " + tongLoai);
        for (int i = 0; i < JtableLoai.getColumnCount(); i++) {
            Class<?> col = JtableLoai.getColumnClass(i);
            JtableLoai.setDefaultEditor(col, null);
        }
        
    }
    private void txtTenLoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenLoaiKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = new DefaultTableModel();
       table.addColumn("Mã nhóm");
        table.addColumn("Tên nhóm thực đơn");
        table.addColumn("Màu sắc");
        ArrayList<Loai> arrayLoai = new ArrayList<>();
        arrayLoai = cn.SearchLoai(txtTenLoai.getText());
        int  tongBan = 0;
        if (arrayLoai.size() > 0) {
           
            for (Loai loai : arrayLoai) {
                tongBan++;
                table.addRow(new Object[]{loai.GetMaLoai(), loai.GetTenLoai(), loai.GetMauSac()});
            }

        }
        lbTongsoloai.setText("Tổng số nhóm món: " + tongBan);
        JtableLoai.setModel(table);
        for (int i = 0; i < JtableLoai.getColumnCount(); i++) {
            Class<?> col = JtableLoai.getClass();
            JtableLoai.setDefaultEditor(col, null);
        }
    }//GEN-LAST:event_txtTenLoaiKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DLThemLoaiMon themloai = new DLThemLoaiMon(MainUI.ManagerForm.main, true);
        themloai.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int row = -1;
        row = JtableLoai.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhóm thực đơn cần sửa thông tin!");
        }
        else
        {
            String mamon = (String )JtableLoai.getValueAt(row, 0);
            DlSuaLoaiMon suamon = new DlSuaLoaiMon(MainUI.ManagerForm.main, true, mamon);
            suamon.setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int[] dsXoa = JtableLoai.getSelectedRows();
        if (dsXoa.length <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn loại để xóa!");
        }
        else
        {
            ArrayList<String> listMaLoai = new ArrayList<String>();
            String tenLoai = "";
            for (int i : dsXoa) {
                String ma = (String) JtableLoai.getValueAt(i, 0);
                listMaLoai.add(ma);
                String tenloai = (String) JtableLoai.getValueAt(i, 1);
                tenLoai += tenloai + " \n";
            }
            int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa nhóm thực đơn: " + tenLoai, "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                boolean isXoa = cn.DeleteNhom(listMaLoai);
                if (isXoa) {
                    loaiMon.fillTableLoaiMon();
                    loaiMon.updateUI();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Không xóa được bàn!");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableLoai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpquanlymon;
    private javax.swing.JLabel lbTongsoloai;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
