/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyUI;

import Data.ConnectDB;
import Models.Loai;
import Models.ThucDon;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class JpQuanLyMon extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLyMon
     */
    public static JpQuanLyMon jpThucdon;
    ConnectDB cn = new ConnectDB();

    public JpQuanLyMon() {
        initComponents();
        jpThucdon = this;
        fillCbbMon();
        fillTableMon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpquanlymonan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableMon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenmon = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbTongsomon = new javax.swing.JLabel();
        cbbNhommon = new javax.swing.JComboBox<>();
        lbNhommon = new javax.swing.JLabel();

        jpquanlymonan.setBackground(new java.awt.Color(255, 255, 255));

        JtableMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtableMon);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel1.setText("Tìm món");

        txtTenmon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenmonKeyReleased(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 204, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 204, 204));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 204, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lbTongsomon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongsomon.setText("Tổng số món:");

        cbbNhommon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbNhommon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNhommonItemStateChanged(evt);
            }
        });

        lbNhommon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNhommon.setForeground(new java.awt.Color(0, 153, 153));
        lbNhommon.setText("Nhóm món");

        javax.swing.GroupLayout jpquanlymonanLayout = new javax.swing.GroupLayout(jpquanlymonan);
        jpquanlymonan.setLayout(jpquanlymonanLayout);
        jpquanlymonanLayout.setHorizontalGroup(
            jpquanlymonanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpquanlymonanLayout.createSequentialGroup()
                .addGroup(jpquanlymonanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpquanlymonanLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnThem)
                        .addGap(77, 77, 77)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpquanlymonanLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jpquanlymonanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpquanlymonanLayout.createSequentialGroup()
                                .addComponent(lbNhommon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(cbbNhommon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTongsomon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jpquanlymonanLayout.setVerticalGroup(
            jpquanlymonanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpquanlymonanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpquanlymonanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNhommon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNhommon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTongsomon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpquanlymonanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1015, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpquanlymonan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpquanlymonan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void fillTableMon(String ma) {
        DefaultTableModel tbmodel = new DefaultTableModel();
        tbmodel.addColumn("Mã món");
        tbmodel.addColumn("Tên món");
        tbmodel.addColumn("Mã loại");
        tbmodel.addColumn("Đơn giá");
        tbmodel.addColumn("Đơn vị tính");
        ArrayList<ThucDon> arrayMon = new ArrayList<>();
        arrayMon = cn.GetThucDon(ma);
        int tongMon = 0;
        if (arrayMon.size() > 0) {

            for (ThucDon thucdon : arrayMon) {
                tongMon++;
                tbmodel.addRow(new Object[]{thucdon.GetMaMon(), thucdon.GetTenMon(), thucdon.GetMaLoai(), thucdon.GetDonGia(), thucdon.GetDVT()});
            }

        }
        lbTongsomon.setText("Tổng số món: " + tongMon);
        JtableMon.setModel(tbmodel);
        for (int i = 0; i < JtableMon.getColumnCount(); i++) {
            Class<?> col = JtableMon.getColumnClass(i);
            JtableMon.setDefaultEditor(col, null);
        }
    }

    public void fillCbbMon() {
        Vector array = cn.GetNhomMon();
        if (array != null) {
            DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel(array);
            cbbNhommon.setModel(cbbmodel);
        } else {
            JOptionPane.showMessageDialog(null, "Không có nhóm nào !");
        }
    }
    private void txtTenmonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenmonKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tbmodel = new DefaultTableModel();
        tbmodel.addColumn("Mã món");
        tbmodel.addColumn("Tên món");
        tbmodel.addColumn("Mã loại");
        tbmodel.addColumn("Đơn giá");
        tbmodel.addColumn("Đơn vị tính");
        ArrayList<ThucDon> arrayMon = new ArrayList<>();
        arrayMon = cn.SearchMon(txtTenmon.getText());
        int tongMon = 0;
        if (arrayMon.size() > 0) {

            for (ThucDon thucdon : arrayMon) {
                tongMon++;
                tbmodel.addRow(new Object[]{thucdon.GetMaMon(), thucdon.GetTenMon(), thucdon.GetMaLoai(), thucdon.GetDonGia(), thucdon.GetDVT()});
            }

        }
        lbTongsomon.setText("Tổng số món: " + tongMon);
        JtableMon.setModel(tbmodel);
        for (int i = 0; i < JtableMon.getColumnCount(); i++) {
            Class<?> col = JtableMon.getColumnClass(i);
            JtableMon.setDefaultEditor(col, null);
        }

    }//GEN-LAST:event_txtTenmonKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DlThemMon themMon = new DlThemMon(MainUI.ManagerForm.main, true);
        themMon.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int row = -1;
        row = JtableMon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn cần sửa thông tin!");
        } else {
            String maban = (String) JtableMon.getValueAt(row, 0);
            DlSuaMon suaMon = new DlSuaMon(MainUI.ManagerForm.main, true, maban);
            suaMon.setVisible(true);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = JtableMon.getSelectedRows();

        if (selectedRows.length <= 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn món nào !");
        } else {
            ArrayList<String> ListMaBan = new ArrayList<String>();
            String sp = "";
            for (int i : selectedRows) {
                String ma = (String) JtableMon.getValueAt(i, 0);
                ListMaBan.add(ma);
                String tenban = (String) JtableMon.getValueAt(i, 1);

                sp += tenban + "\n";
            }
            int qs;
            qs = JOptionPane.showConfirmDialog(null, "Xóa món: \n " + sp, "Xóa món", JOptionPane.YES_NO_OPTION);
            if (qs == JOptionPane.YES_OPTION) {
                boolean xoa = cn.DeleteThucDon(ListMaBan);
                if (xoa == true) {
                    fillTableMon(null);
                    JOptionPane.showMessageDialog(null, "Xóa món thành công!");
                } else {
                    JOptionPane.showMessageDialog(null, "Không xóa được món !");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbbNhommonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNhommonItemStateChanged
        // TODO add your handling code here:
        Loai mon = (Loai) cbbNhommon.getSelectedItem();
        fillTableMon(mon.GetMaLoai());

    }//GEN-LAST:event_cbbNhommonItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableMon;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbNhommon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpquanlymonan;
    private javax.swing.JLabel lbNhommon;
    private javax.swing.JLabel lbTongsomon;
    private javax.swing.JTextField txtTenmon;
    // End of variables declaration//GEN-END:variables
}
