/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SettingUI;

import java.awt.BorderLayout;

/**
 *
 * @author pc
 */
public class JpSetting extends javax.swing.JPanel {

    /**
     * Creates new form JpSetting
     */
    public JpSetting() {
        initComponents();
        fillThongtin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpButton = new javax.swing.JPanel();
        btnThongtin = new javax.swing.JButton();
        btnDoimk = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jpSettingContent = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1290, 525));

        jpButton.setBackground(new java.awt.Color(0, 153, 0));
        jpButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThongtin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infor.png"))); // NOI18N
        btnThongtin.setText("Thông tin");
        btnThongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongtinActionPerformed(evt);
            }
        });

        btnDoimk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change_pass.png"))); // NOI18N
        btnDoimk.setText("Đổi mật khẩu");
        btnDoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoimkActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_address_20px.png"))); // NOI18N
        jButton3.setText("Liên lạc");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonLayout = new javax.swing.GroupLayout(jpButton);
        jpButton.setLayout(jpButtonLayout);
        jpButtonLayout.setHorizontalGroup(
            jpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnDoimk, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnThongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpButtonLayout.setVerticalGroup(
            jpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnThongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jpSettingContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpSettingContentLayout = new javax.swing.GroupLayout(jpSettingContent);
        jpSettingContent.setLayout(jpSettingContentLayout);
        jpSettingContentLayout.setHorizontalGroup(
            jpSettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
        );
        jpSettingContentLayout.setVerticalGroup(
            jpSettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpSettingContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSettingContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillThongtin(){
        jpSettingContent.removeAll();
        jpSettingContent.setLayout(new BorderLayout());
        JpThongtin thongtin = new JpThongtin();
        jpSettingContent.add(thongtin);
    }
    private void fillDoiMatkhau(){
        jpSettingContent.removeAll();
        jpSettingContent.setLayout(new BorderLayout());
        JpDoimk thongtin = new JpDoimk();
        jpSettingContent.add(thongtin);
    }
    private void fillLienLac(){
        jpSettingContent.removeAll();
        jpSettingContent.setLayout(new BorderLayout());
        JpLienLac lienlac = new JpLienLac();
        jpSettingContent.add(lienlac);
    }
    private void btnThongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongtinActionPerformed
        // TODO add your handling code here:

        fillThongtin();
    }//GEN-LAST:event_btnThongtinActionPerformed

    private void btnDoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoimkActionPerformed
        // TODO add your handling code here:
        fillDoiMatkhau();
    }//GEN-LAST:event_btnDoimkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fillLienLac();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoimk;
    private javax.swing.JButton btnThongtin;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jpButton;
    private javax.swing.JPanel jpSettingContent;
    // End of variables declaration//GEN-END:variables
}
