/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BanHangUI;

import Data.ConnectDB;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import Models.Ban;

/**
 *
 * @author pc
 */
public class DlGopBan extends javax.swing.JDialog {

    /**
     * Creates new form DlGopBan
     */
    int maBan, maHD;
    String tenBan;
    ConnectDB cn = new ConnectDB();

    public DlGopBan(java.awt.Frame parent, boolean modal, int maban, String tenban, int mahd) {
        super(parent, modal);
        initComponents();
        maBan = maban;
        maHD = mahd;
        tenBan = tenban;
        fillCbb();
        lbGopban.setText("Gộp bàn " + tenban);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpGopBan = new javax.swing.JPanel();
        lbGopban = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbBanDangPhucVu = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        JpGopBan.setBackground(new java.awt.Color(0, 153, 153));
        JpGopBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        lbGopban.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGopban.setForeground(new java.awt.Color(255, 255, 255));
        lbGopban.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGopban.setText("GỘP BÀN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Đến bàn");

        cbBanDangPhucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnOK.setBackground(new java.awt.Color(0, 0, 255));
        btnOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(255, 51, 51));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpGopBanLayout = new javax.swing.GroupLayout(JpGopBan);
        JpGopBan.setLayout(JpGopBanLayout);
        JpGopBanLayout.setHorizontalGroup(
            JpGopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbGopban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpGopBanLayout.createSequentialGroup()
                .addGroup(JpGopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpGopBanLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cbBanDangPhucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpGopBanLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnOK)
                        .addGap(46, 46, 46)
                        .addComponent(btnHuy)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        JpGopBanLayout.setVerticalGroup(
            JpGopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpGopBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGopban, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(JpGopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBanDangPhucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(JpGopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnHuy))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpGopBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpGopBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        Ban banChuyen = new Ban(maBan, tenBan, "Trống");
        if (cn.UpdateBan(banChuyen)) {
            Ban banChon = (Ban) cbBanDangPhucVu.getSelectedItem();
//            Ban den = new Ban(banChon.GetMaBan(), banChon.GetTenBan(), "Đang phục vụ");
            String maHd = String.valueOf(maHD);
            String maban = String.valueOf(banChon.GetMaBan());
//            if (cn.UpdateBan(den)) {
                if (cn.UpdateHDBan(maHd, maban)){
                    JOptionPane.showMessageDialog(null, "Chuyển bàn thành công!");
                    JpBanhang.banhang.fillBan();
                    JpBanhang.banhang.updateUI();
                    JpGoiMon.goimon.removeAll();
                    dispose();
                }
//            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed
    private void fillCbb() {
        Vector array = cn.GetBanDangPhucVu();
        if (array != null) {
            DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel(array);
            cbBanDangPhucVu.setModel(cbbmodel);
        } else {
            JOptionPane.showMessageDialog(null, "Không có bàn đang phục vụ nào !");
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpGopBan;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbBanDangPhucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbGopban;
    // End of variables declaration//GEN-END:variables

}
