/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BanHangUI;

import Data.ConnectDB;
import Models.Ban;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author pc
 */
public class JpBanhang extends javax.swing.JPanel {

    /**
     * Creates new form JpBanhang
     */
    public ConnectDB cn = new ConnectDB();
    ArrayList<Ban> arrayBan = new ArrayList<Ban>();
    ArrayList<Ban> ban = new ArrayList<>();
    int maBan;
    public static JpBanhang banhang;

    public JpBanhang() {
        initComponents();
        banhang = this;
        btnTrong.setBackground(Color.blue);
        btnDangphucvu.setBackground(Color.red);
        btnDattruoc.setBackground(Color.yellow);
        fillBan();
    }

    public void fillBan() {
        arrayBan = cn.GetBan(0);
        if (arrayBan.size() > 0) {
            jpBan.removeAll();
            JButton[] arrayButtons = new JButton[arrayBan.size()];
            for (int i = 0; i < arrayBan.size(); i++) {
                arrayButtons[i] = new JButton();
                arrayButtons[i].setName(String.valueOf(arrayBan.get(i).GetMaBan()));
                String[] mb = arrayBan.get(i).GetTenBan().split(" ");
                arrayButtons[i].setText(mb[1]);
                arrayButtons[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico-Table.png")));
                Border thickBorder = new LineBorder(Color.WHITE, 8);
                arrayButtons[i].setBorder(thickBorder);
                arrayButtons[i].setBackground(Color.blue);
                arrayButtons[i].setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                arrayButtons[i].setForeground(new java.awt.Color(51, 51, 51));
                if (arrayBan.get(i).GetTrangThai().equals("Đang phục vụ")) {
                    arrayButtons[i].setBackground(Color.red);
                }
                if (arrayBan.get(i).GetTrangThai().equals("Đã đặt trước")) {
                    arrayButtons[i].setBackground(Color.yellow);
                }
                arrayButtons[i].setPreferredSize(new Dimension(90, 70));

                arrayButtons[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        JpGoiMon goimon;
                        ban = cn.GetBan(Integer.parseInt(e.getComponent().getName()));
                        if (ban != null) {
                            goimon = new JpGoiMon(ban.get(0).GetTrangThai(), ban.get(0).GetTenBan(), ban.get(0).GetMaBan());
                            jpChonmon.removeAll();
                            jpChonmon.setLayout(new BorderLayout());
                            jpChonmon.add(goimon);
                            jpChonmon.updateUI();
                        }
                    }
                });
                jpBan.add(arrayButtons[i]);
                jpBan.updateUI();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpBan = new javax.swing.JPanel();
        btnDangphucvu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnTrong = new javax.swing.JButton();
        btnDattruoc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpChonmon = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        jpBan.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Trống");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Đang phục vụ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Đã đặt trước");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTrong)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangphucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(btnDattruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDattruoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDangphucvu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTrong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jpChonmon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        javax.swing.GroupLayout jpChonmonLayout = new javax.swing.GroupLayout(jpChonmon);
        jpChonmon.setLayout(jpChonmonLayout);
        jpChonmonLayout.setHorizontalGroup(
            jpChonmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        jpChonmonLayout.setVerticalGroup(
            jpChonmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpChonmon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpChonmon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangphucvu;
    private javax.swing.JButton btnDattruoc;
    private javax.swing.JButton btnTrong;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpBan;
    private javax.swing.JPanel jpChonmon;
    // End of variables declaration//GEN-END:variables
}
