/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BanHangUI;

import Data.ConnectDB;
import MainUI.ManagerForm;
import Models.Loai;
import Models.ThucDon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class JpThucDon extends javax.swing.JPanel {

    /**
     * Creates new form JpThucDon
     */
    public ConnectDB cn = new ConnectDB();
    public String gioden, tenban;
    public int maban;
    public ArrayList<ThucDon> arrdsmon;
    NumberFormat chuyentien = new DecimalFormat("#,###,###");
    public static JpThucDon thucdon;

    public JpThucDon() {
        initComponents();
        thucdon = this;
        fillLoai();
    }

    public void fillLoai() {
        ArrayList<Loai> arrayLoai = cn.GetLoai();
        if (arrayLoai.size() > 0) {
            JButton btn;
            JpLoaiThucDon.setLayout(new BoxLayout(JpLoaiThucDon, BoxLayout.PAGE_AXIS));
            JpLoaiThucDon.removeAll();
            jpChonMon.setLayout(new FlowLayout(FlowLayout.CENTER));
            for (Loai loai : arrayLoai) {
                btn = new JButton(loai.GetTenLoai());
                btn.setName(loai.GetMaLoai());
                btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
                btn.setMaximumSize(new Dimension(140, 40));
                btn.setForeground(Color.decode("#331a00"));
                btn.setBackground(Color.decode(loai.GetMauSac()));
                btn.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
                btn.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        lbNhomThucDon.setText("    Nhóm " + loai.GetTenLoai());
                        lbNhomThucDon.setBackground(Color.decode(loai.GetMauSac()));
                        ArrayList<ThucDon> arrThucDon = cn.GetThucDon(loai.GetMaLoai());
                        jpChonMon.removeAll();
                        jpChonMon.updateUI();
                        jpChonMon.setLayout(new BoxLayout(jpChonMon, BoxLayout.PAGE_AXIS));
                        if (arrThucDon != null) {
                            JPanel[] pn = new JPanel[arrThucDon.size()];
                            //jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.PAGE_AXIS));
                            for (int i = 0; i < arrThucDon.size(); i++) {
                                pn[i] = new JPanel();
                                pn[i].setName(arrThucDon.get(i).GetMaMon());
                                pn[i].setCursor(new Cursor(Cursor.HAND_CURSOR));
                                pn[i].setBackground(Color.decode("#dfff80"));
                                pn[i].setBorder(BorderFactory.createLineBorder(Color.decode("#a3a375"), 2));
                                pn[i].setPreferredSize(new Dimension(128, 60));
                                pn[i].add(new JLabel(arrThucDon.get(i).GetTenMon())).setFont(new java.awt.Font("Tahoma", 1, 12));
                                pn[i].add(new JLabel(String.valueOf(chuyentien.format(arrThucDon.get(i).GetDonGia())) + " VNĐ/ " + arrThucDon.get(i).GetDVT())).setForeground(Color.decode("#ff0000"));
                                pn[i].addMouseListener(new MouseAdapter() {
                                    @Override
                                    public void mousePressed(MouseEvent e) {

                                        DlSoLuong sl = new DlSoLuong(ManagerForm.main, true, e.getComponent().getName(), tenban, maban);
                                        sl.gioden = gioden;
                                        sl.setVisible(true);
                                    }
                                });
                                jpChonMon.add(pn[i]);
                                jpChonMon.updateUI();
                            }
                        }

                    }
                });
                JpLoaiThucDon.add(btn);
                JpLoaiThucDon.updateUI();

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpLoaiThucDon = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpChonMon = new javax.swing.JPanel();
        lbNhomThucDon = new javax.swing.JLabel();

        JpLoaiThucDon.setBackground(Color.decode("#e6e6e6"));
        JpLoaiThucDon.setLayout(null);

        jPanel1.setBackground(Color.decode("#e6e6e6"));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAlignmentX(0.0F);

        jpChonMon.setBackground(Color.decode("#e6e6e6"));
        jpChonMon.setAutoscrolls(true);
        jpChonMon.setPreferredSize(new java.awt.Dimension(289, 420));

        javax.swing.GroupLayout jpChonMonLayout = new javax.swing.GroupLayout(jpChonMon);
        jpChonMon.setLayout(jpChonMonLayout);
        jpChonMonLayout.setHorizontalGroup(
            jpChonMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpChonMonLayout.setVerticalGroup(
            jpChonMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbNhomThucDon.setBackground(new java.awt.Color(153, 0, 153));
        lbNhomThucDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNhomThucDon.setForeground(new java.awt.Color(253, 253, 253));
        lbNhomThucDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhomThucDon.setText("                          Chọn món");
        lbNhomThucDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbNhomThucDon.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbNhomThucDon.setIconTextGap(7);
        lbNhomThucDon.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpChonMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhomThucDon, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbNhomThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpChonMon, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpLoaiThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(JpLoaiThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpLoaiThucDon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpChonMon;
    private javax.swing.JLabel lbNhomThucDon;
    // End of variables declaration//GEN-END:variables
}
